name: jaffle_shop
version: '1.0.0'
config-version: 2

profile: jaffle_shop

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
