dagster_university_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../data/staging/data.duckdb'
      extensions:
        - spatial
        - parquet
    dagster:
      type: duckdb
      path: '../data/staging/data.duckdb'
      extensions:
        - spatial
        - parquet