name: pip-install-check-ai-driven-data-engineering

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - dagster_university/ai_driven_data_engineering/pyproject.toml

jobs:
  check:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/template-pip-install-check.yml
    with:
      working_directory: ./dagster_university/ai_driven_data_engineering
      module_name: ai_driven_data_engineering
